Fix regression for --show-plugin-list
When --show-plugin-list option of insights-cli command is called
with report archive, the following error occurs:

AttributeError: 'module' object has no attribute 'replace'

The reason is that the commit #ba6abac changed get_module_names()
to accept package name instead of module object.

This patch changes the get_module_names() call to pass package
name.